source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, RegisterActivateView, UserDetailView, UserIndexView, UserChangeView, \
    UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='create'),
    path('activate/<uuid:token>/', RegisterActivateView.as_view(), name='activate'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('', UserIndexView.as_view(), name='user_list'),
    path('<int:pk>/change/', UserChangeView.as_view(), name='change'),
    path('<int:pk>/password_change/', UserPasswordChangeView.as_view(), name='password_change')
]

source/main/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path, include

from webapp.views import IndexView, ProductView, ProductCreateView, ProductUpdateView, ProductDeleteView, \
    ReviewUpdateView, ReviewDeleteView, ReviewCreateView, review_mass_action_view, ReviewView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),

    path('product/', include([
        path('<int:pk>/', ProductView.as_view(), name='product_view'),
        path('add/', ProductCreateView.as_view(), name='product_create'),
        path('<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
        path('<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
        path('<int:pk>/reviews/add/', ReviewCreateView.as_view(), name='review_create')
    ])),
    path('review/', include([
        path('<int:pk>/', include([
            path('', ReviewView.as_view(), name='review_view'),
            path('update/', ReviewUpdateView.as_view(), name='review_update'),
            path('delete/', ReviewDeleteView.as_view(), name='review_delete'),
        ])),
        path('mass-action/', review_mass_action_view, name='review_mass_action'),
    ]))
]

source/webapp/models.py
import math

from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.
CATEGORY_CHOICES = [
    ('other', 'Разное'),
    ('phone_repair', 'Ремонт мобильных телефонов'),
    ('plumbing', 'Сантехника'),
    ('tv_repair', 'Ремонт телевизоров'),
    ('buy_sell', 'Купи-продай')
]
#
# DEFAULT = 'product_pics/default.png'

RATES = [
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5)
]


class Product(models.Model):
    name = models.CharField(max_length=200, null=False, blank=False, verbose_name='Название')
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default=CATEGORY_CHOICES[0][0],
                                verbose_name='Категории')
    description = models.TextField(max_length=3000, null=True, blank=True, verbose_name='Описание')
    image = models.ImageField(null=True, blank=True, upload_to='product_pics', verbose_name='Картинка')

    def __str__(self):
        return f'{self.name}'

    def avg_rating(self):
        ratings = Review.objects.filter(product=self.pk)
        count = 0
        for r in ratings:
            count += r.rating
        try:
            avg = count / len(ratings)
        except ZeroDivisionError:
            avg = 0
        return math.ceil(avg)

    class Meta:
        verbose_name = 'Товар-Услуга'
        verbose_name_plural = 'Товары-Услуги'


class Review(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_DEFAULT, default=1,
                               related_name='reviews', verbose_name='Автор')
    product = models.ForeignKey('webapp.Product', related_name='reviews', on_delete=models.CASCADE,
                                verbose_name='Товар-Услуга')
    text = models.TextField(max_length=3000, null=False, blank=False, verbose_name='Текст')
    rating = models.IntegerField(choices=RATES, null=False, blank=False, verbose_name='Оценка')

    def __str__(self):
        return f'{self.author} - {self.rating}'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

source/webapp/forms.py
from django import forms
from webapp.models import Product, Review


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label="Search")


class ProductForm(forms.ModelForm):
    description = forms.CharField(max_length=2000, required=False, label="Description",
                                  widget=forms.Textarea)
    image = forms.ImageField(required=False, label='image')

    class Meta:
        model = Product
        fields = ['name', 'category', 'description', 'image']
        widgets = {'category': forms.Select}


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['text', 'rating']
        widgets = {'rating': forms.Select}

source/webapp/views.py
from django.shortcuts import render

# Create your views here.

source/webapp/views/base_views.py
from django.db.models import Q
from django.views.generic import ListView as DjangoListView

from webapp.forms import SimpleSearchForm


class SearchView(DjangoListView):
    search_form_class = SimpleSearchForm
    search_form_field = 'search'
    search_fields = []

    def get(self, request, *args, **kwargs):
        self.search_form = self.get_search_form()
        self.search_value = self.get_search_value(self.search_form)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['search_form'] = self.search_form
        context['search_value'] = self.search_value
        return context

    def get_queryset(self):
        data = super().get_queryset()
        query = self.get_query(self.search_value)
        data = data.filter(query)
        return data

    def get_search_form(self):
        return self.search_form_class(data=self.request.GET)

    def get_search_value(self, form):
        search_value = None
        if form.is_valid():
            search_value = form.cleaned_data.get(self.search_form_field, None)
        return search_value

    def get_query(self, search_value):
        query = Q()
        if search_value:
            for field in self.search_fields:
                kwargs = {field: search_value}
                query = query | Q(**kwargs)
        return query

source/webapp/views/product_views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, \
    UserPassesTestMixin
from django.core.paginator import Paginator
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.utils.timezone import make_naive
from django.views.generic import View, DetailView, CreateView, UpdateView, DeleteView

from .base_views import SearchView
from webapp.models import Product
from ..forms import ProductForm


class IndexView(SearchView):
    template_name = 'index.html'
    context_object_name = 'products'
    paginate_by = 6
    paginate_orphans = 0
    model = Product
    search_fields = ['name__icontains', 'author__icontains']


class ProductView(DetailView):
    template_name = 'product/product_view.html'
    model = Product
    paginate_reviews_by = 5
    paginate_reviews_orphans = 0

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        reviews, page, is_paginated = self.paginate_reviews(self.object)
        context['reviews'] = reviews
        context['page_obj'] = page
        context['is_paginated'] = is_paginated

        return context

    def paginate_reviews(self, product):
        reviews = product.reviews.all().order_by('-rating')
        if reviews.count() > 0:
            paginator = Paginator(reviews, self.paginate_reviews_by, orphans=self.paginate_reviews_orphans)
            page_number = self.request.GET.get('page', 1)
            page = paginator.get_page(page_number)
            is_paginated = paginator.num_pages > 1  # page.has_other_pages()
            return page.object_list, page, is_paginated
        else:
            return reviews, None, False


class ProductCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'product/product_create.html'
    form_class = ProductForm
    model = Product
    permission_required = 'webapp.add_product'

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk})


class ProductUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'product/product_update.html'
    form_class = ProductForm
    model = Product
    permission_required = 'webapp.change_product'

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk})


class ProductDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'product/product_delete.html'
    model = Product
    permission_required = 'webapp.delete_product'
    success_url = reverse_lazy('index')

source/webapp/views/review_views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.shortcuts import  get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import DetailView, DeleteView, UpdateView, CreateView
from webapp.forms import ProductForm, ReviewForm
from webapp.models import Review, Product


class ReviewCreateView(LoginRequiredMixin, CreateView):
    model = Review
    template_name = 'review/review_create.html'
    form_class = ReviewForm

    def form_valid(self, form):
        product = get_object_or_404(Product, pk=self.kwargs.get('pk'))
        review = form.save(commit=False)
        review.product = product
        review.author = self.request.user
        review.save()
        return redirect('webapp:product_view', pk=product.pk)


class ReviewUpdateView(PermissionRequiredMixin, UpdateView):
    model = Review
    template_name = 'review/review_update.html'
    form_class = ReviewForm
    permission_required = 'webapp.change_review'

    def has_permission(self):
        review = self.get_object()
        return super().has_permission() or review.author == self.request.user

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.product.pk})


class ReviewDeleteView(PermissionRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Review
    permission_required = 'webapp.delete_review'

    def test_func(self):
        review = Review.objects.get(pk=self.kwargs.get('pk'))
        return self.request.user == review.author or self.request.user.has_perm('webapp.delete_review')

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.product.pk})


class ReviewView(DetailView):
    template_name = 'review/review_view.html'
    model = Review
    context_object_name = 'reviews'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


@login_required
def review_mass_action_view(request):
    if request.method == 'POST':
        ids = request.POST.getlist('selected_reviews', [])
        if 'delete' in request.POST:
            Review.objects.filter(id__in=ids).delete()
    return redirect('webapp:index')

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="zxx">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}My Site{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans+Condensed:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Amatic+SC&family=Open+Sans+Condensed:wght@300&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet"
          href="cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css"
          integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block styles %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-info sticky-top">
    <div class="container-sm">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="menu w-100 font-weight-bold navbar-nav mr-auto ml-md-5">
                <li><a href="{% url 'webapp:index' %}" class="text-uppercase text-decoration-none px-md-3 py-md-2">Home</a>
                </li>
                {% if request.user.is_authenticated %}
                    {% if perms.accounts.can_view_users_list %}
                        <li><a href="{% url 'accounts:user_list' %}" class="text-uppercase text-decoration-none px-md-3 py-md-2">Users</a>
                    </li>
                    {% endif %}
                    {% if perms.webapp.add_product %}
                        <li><a href="{% url 'webapp:product_create' %}" class="text-uppercase text-decoration-none px-md-3 py-md-2">Add New Product</a>
                    {% endif %}
                    {% block menu %}{% endblock %}
                    <li><a href="{% url 'accounts:detail' request.user.pk %}" class="w-100">{{ request.user.get_full_name }}</a></li>
                    <li><a href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}"
                           class="text-uppercase text-decoration-none px-md-3 py-md-2">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:login' %}?next={{ request.get_full_path }}"
                           class="text-uppercase text-decoration-none px-md-3 py-md-2">Login</a></li>
                    <li><a href="{% url 'accounts:create' %}?next={{ request.get_full_path }}"
                           class="text-uppercase text-decoration-none px-md-3 py-md-2">Sign Up</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container-sm">
    {% include "partial/messages.html" %}
    {% block content %}{% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"
        integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.bundle.js' %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

source/webapp/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Main{% endblock %}

{% block menu %}
    <li class="d-inline-block float-right">{% include 'partial/simple_search.html' %}</li>
{% endblock %}

{% block content %}
    <h1 class="text-uppercase text-info amatic-text d-flex justify-content-center font-weight-bold pt-4">Products and
        Services</h1>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
    <div class="row row-cols-1 row-cols-md-3">
        {% for product in products %}
            <div class="col-sm-6">
                <div class="card border-info mb-3">
                    <div class="d-flex bd-highlight list-group-item-info">
                        <div class="mr-auto p-2 bd-highlight">
                            <h3><a href="{% url 'webapp:product_view' product.pk %}"
                                   class="text-decoration-none list-group-item-info font-weight-bold">{{ product.name }}</a>
                            </h3>
                            <h4 class="list-group-item-info font-weight-bold"><span
                                    class="text-info font-weight-light mr-1">Category:</span> {{ product.get_category_display }}
                            </h4>
                            {% if product.image %}
                                <img class="avatar" src="{{ product.image.url }}" width="250" height="250"
                                     alt="#">
                            {% else %}
                                <img class="avatar" src="{% static 'img/default.png' %}" width="250" height="250"
                                     alt="product picture">
                            {% endif %}
                        </div>
                    </div>
                    <div class="card-body text-info list-group-item-info">
                        <h4 class="card-text mr-auto">about: <span
                                class="pl-2 list-group-item-info font-weight-bold">{{ product.description }}</span>
                        </h4>
                        <h4 class="card-text mr-auto">rating:
                            <span class="pl-2 list-group-item-info font-weight-bold">
                                {% if product.avg_rating == 1 %}
                                    <i class="fas fa-star"></i>
                                {% elif product.avg_rating == 2 %}
                                    <i class="fas fa-star text-dark"></i>
                                    <i class="fas fa-star"></i>
                                {% elif product.avg_rating == 3 %}
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                {% elif product.avg_rating == 4 %}
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                {% elif product.avg_rating == 5 %}
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                {% endif %}
                            </span>
                        </h4>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}