source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, RegisterActivateView, UserDetailView, UserIndexView, UserChangeView, \
    UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='create'),
    path('activate/<uuid:token>/', RegisterActivateView.as_view(), name='activate'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('', UserIndexView.as_view(), name='user_list'),
    path('<int:pk>/change/', UserChangeView.as_view(), name='change'),
    path('<int:pk>/password_change/', UserPasswordChangeView.as_view(), name='password_change')
]

source/main/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from uuid import uuid4
from django.contrib.auth.models import AbstractUser
from django.utils.timezone import now
from datetime import timedelta

TOKEN_TYPE_REGISTER = 'register'
TOKEN_TYPE_PASSWORD_RESET = 'password_reset'
TOKEN_TYPE_CHOICES = (
    (TOKEN_TYPE_REGISTER, 'Регистрация'),
    (TOKEN_TYPE_PASSWORD_RESET, 'Восстановление пароля')
)


class AuthToken(models.Model):
    token = models.UUIDField(verbose_name='Токен', default=uuid4)
    user: AbstractUser = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,
                                           related_name='tokens', verbose_name='Пользователь')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    life_days = models.IntegerField(default=7, verbose_name='Срок действия (в днях)')
    type = models.CharField(max_length=20, choices=TOKEN_TYPE_CHOICES,
                            default=TOKEN_TYPE_REGISTER, verbose_name='Тип токена')

    @classmethod
    def get_token(cls, token):
        try:
            return cls.objects.get(token=token)
        except cls.DoesNotExist:
            return None

    def is_alive(self):
        return (self.created_at + timedelta(days=self.life_days)) >= now()

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'Аутентификационный токен'
        verbose_name_plural = 'Аутентификационные токены'


class Profile(models.Model):
    user: AbstractUser = models.OneToOneField(get_user_model(), related_name='profile', on_delete=models.CASCADE,
                                              verbose_name='Пользователь')
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Аватар')
    github_profile = models.URLField(null=True, blank=True, verbose_name='Профиль на GitHub')
    about_self = models.CharField(null=True, blank=True, max_length=2000, verbose_name='О себе')

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'
        permissions = [
            ('can_view_users_list', 'может видеть список пользователей')
        ]

source/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError

from accounts.models import Profile


class ProfileForm(forms.ModelForm):
    about_self = forms.CharField(required=False, max_length=2000, widget=forms.Textarea, label='О себе')
    avatar = forms.ImageField(required=False, label='avatar')
    github_profile = forms.URLField(required=False, label='Профиль на GitHub')

    class Meta:
        model = Profile
        fields = ['avatar', 'github_profile', 'about_self']


class MyUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=20, required=False, label='First name')
    last_name = forms.CharField(max_length=25, required=False, label='Last name')
    email = forms.EmailField(max_length=30, required=True, label='e-mail')

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name', 'email']
        fields_classes = {'username': UsernameField}

    def clean(self):
        cleaned_data = super().clean()
        errors = []
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        if first_name == '' and last_name == '':
            errors.append(ValidationError('One of fields should be filled. First name or last name!'))
        if first_name == '' and last_name != '':
            return cleaned_data
        if first_name != '' and last_name == '':
            return cleaned_data
        if errors:
            raise ValidationError(errors)


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label="Новый пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label="Старый пароль", strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['password', 'password_confirm', 'old_password']

source/accounts/views/user_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.contrib.auth import login, get_user_model
from django.urls import reverse
from django.utils.http import urlencode

from accounts.forms import MyUserCreationForm, UserChangeForm, ProfileChangeForm, PasswordChangeForm
from django.views.generic import CreateView, View, DetailView, ListView, UpdateView

from accounts.models import AuthToken
from webapp.forms import SimpleSearchForm


class RegisterView(CreateView):
    model = User
    template_name = 'user/user_create.html'
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next:
            next_url = self.request.POST.get('next')
        if not next:
            next_url = reverse('index')
        return next_url


class RegisterActivateView(View):
    def get(self, request, *args, **kwargs):
        token = AuthToken.get_token(self.kwargs.get('token'))
        if token:
            if token.is_alive():
                user = token.user
                user.is_active = True
                user.save()
                login(request, user)
            token.delete()
        return redirect('index')


class UserDetailView(DetailView):
    model = get_user_model()
    template_name = 'user/user_detail.html'
    context_object_name = 'user_obj'
    paginate_related_by = 5
    paginate_related_orphans = 0


class UserIndexView(ListView, UserPassesTestMixin):
    context_object_name = 'users'
    model = get_user_model()
    template_name = 'user/user_list.html'
    paginate_by = 5
    paginate_orphans = 1

    def test_func(self):
        return self.request.user.has_perm('accounts.can_view_users_list')

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(username__icontains=self.search_value) | Q(first_name__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class UserChangeView(UserPassesTestMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user/user_change.html'
    context_object_name = 'user_obj'

    def test_func(self):
        return self.request.user == self.get_object()

    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
        return super().get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.get_profile_form()
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        form.save()
        profile_form.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form)
        return self.render_to_response(context)

    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
        return ProfileChangeForm(**form_kwargs)

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.object.pk})


class UserPasswordChangeView(UserPassesTestMixin, UpdateView):
    model = get_user_model()
    template_name = 'user/user_password_change.html'
    form_class = PasswordChangeForm
    context_object_name = 'user_obj'

    def test_func(self):
        return self.request.user == self.get_object()

    def get_success_url(self):
        return reverse('accounts:login')

source/accounts/templates/user/user_change.html
{% extends 'base.html' %}

{% block title %}Редактировать пользователя{% endblock %}

{% block menu %}
    {% if request.user == user_obj %}
        <li><a href="{% url "accounts:detail" user_obj.pk %}" class="font-weight-bold text-decoration-none">Cancel</a>
        </li>
        <li><a href="{% url "accounts:password_change" user_obj.pk %}" class="font-weight-bold text-decoration-none">Change
            Password</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1 class="amatic-text font-weight-bold text-secondary">Изменить личные данные</h1>
    <form action="{% url 'accounts:change' user_obj.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'partial/form.html' with form=form fields_only=True %}
        {% include 'partial/form.html' with form=profile_form fields_only=True %}
        <br>
        <input class="btn btn btn-info font-weight-bold text-uppercase" type="submit" value="Submit">
        <a href="{% url "accounts:detail" user_obj.pk %}"
           class="text-uppercase font-weight-bold text-decoration-none btn btn btn-info ml-5">Cancel</a>
    </form>
    <p></p>
{% endblock %}

source/accounts/templates/user/user_create.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}

{% block auth_menu %}
    {% with request.GET.next as next_url %}
        <li><a href="{% url 'accounts:login' %}{% if next_url %}?next={{ next_url }}{% endif %}">Login</a></li>
        <li><a href="{% url 'accounts:create' %}{% if next_url %}?next={{ next_url }}{% endif %}">Sign Up</a></li>
    {% endwith %}
{% endblock %}

{% block content %}
    <h1>Sign Up</h1>
    {% include 'partial/form.html' with form_method='post' button_text="Sign Up" %}
{% endblock %}

source/accounts/templates/user/user_detail.html
{% extends 'base.html' %}

{% block title %}Пользователь{% endblock %}

{% block menu %}
    {% if request.user == user_obj %}
        <li><a href="{% url 'accounts:change' user_obj.pk %}"
               class="font-weight-bold text-decoration-none">Edit</a></li>
        <li><a href="{% url "accounts:password_change" user_obj.pk %}">Change Password</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <h2 class="d-flex justify-content-center amatic-text text-success font-weight-bold">Личная страница
        пользователя</h2>
    <h1 class="d-flex justify-content-center amatic-text text-info font-weight-bold">
        {{ user_obj.get_full_name|default:user_obj.username }}</h1>
    {% if user_obj.profile.avatar %}
        <img class="avatar" src="{{ user_obj.profile.avatar.url }}" width="250" height="250" alt="user picture">
    {% endif %}
    <p class="text-success font-weight-bold d-inline-block pr-2">Имя пользователя:
    <h5 class="font-weight-bold text-info d-inline-block">{{ user_obj.username }}</h5></p>
    <p class="text-success font-weight-bold d-inline-block pr-2">Имя:
    <h5 class="font-weight-bold text-info d-inline-block">{{ user_obj.first_name }}</h5></p>
    <p class="text-success font-weight-bold d-inline-block pr-2">Фамилия:
    <h5 class="font-weight-bold text-info d-inline-block">{{ user_obj.last_name }}</h5></p>
    <p class="text-success font-weight-bold d-inline-block pr-2">О себе:
    <h5 class="font-weight-bold text-info d-inline-block">{{ user_obj.profile.about_self }}</h5></p>
    <p class="text-success font-weight-bold d-inline-block pr-2">Страница на GitHub:
    <h5 class="font-weight-bold text-info d-inline-block"><a
            href="{{ user_obj.profile.github_profile }}">{{ user_obj.profile.github_profile }}</a></h5></p>
    <p class="text-success font-weight-bold d-inline-block pr-2">Почта:
    <h5 class="font-weight-bold text-info d-inline-block">{{ user_obj.email }}</h5></p>
    <h2 class="text-center clear text-success font-weight-bold amatic-text">Мои отзывы:</h2>
    {% include 'partial/review_list.html' %}
{% endblock %}

source/accounts/templates/user/user_list.html
{% extends 'base.html' %}

{% block title %}Пользователь{% endblock %}

{% block menu %}
    <li class="d-inline-block float-right">{% include 'partial/simple_search.html' %}</li>
{% endblock %}

{% block content %}
    {% if perms.accounts.can_view_users_list %}
        {% for user in users %}
            <div class="box text-info d-md-inline-block w-100">
                <h1 class="d-flex justify-content-center amatic-text text-info font-weight-bold"><a
                        href="{% url 'accounts:detail' user.pk %}"
                        class="text-decoration-none text-info">{{ user.profile }}</a>
                </h1>
                {% if user.profile.avatar %}
                    <img class="h-auto d-inline-block float-right" src="{{ user.profile.avatar.url }}" width="250"
                         height="250" alt="user picture">
                {% endif %}
                <div class="">
                    <p class="text-success font-weight-bold d-inline-block pr-2">Имя пользователя: <h5
                        class="font-weight-bold text-info d-inline-block">{{ user.username }}</h5></p>
                    <p class="text-success font-weight-bold d-inline-block pr-2">Имя: <h5
                        class="font-weight-bold text-info d-inline-block">{{ user.first_name }}</h5></p>
                    <p class="text-success font-weight-bold d-inline-block pr-2">Фамилия: <h5
                        class="font-weight-bold text-info d-inline-block">{{ user.last_name }}</h5></p>
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}

source/accounts/templates/user/user_password_change.html
{% extends 'base.html' %}

{% block title %}Смена пароля{% endblock %}

{% block menu %}
    {% if request.user == user_obj %}
        <li><a href="{% url "accounts:detail" user_obj.pk %}" class="font-weight-bold text-decoration-none">Cancel</a></li>
        <li><a href="{% url "accounts:change" user_obj.pk %}" class="font-weight-bold text-decoration-none">Edit Profile</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1 class="text-secondary font-weight-bold amatic-text">Смена пароля</h1>
    {% url "accounts:password_change" user_obj.pk as action_url %}
    {% include 'partial/form.html' with action_url=action_url form_method="post" %}
{% endblock %}